# Generated by Django 4.0.7 on 2023-04-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_DS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_talents', models.CharField(blank=True, choices=[('I request this candidate', 'I request this candidate'), ('I request a candidate who has the same stack', 'I request a candidate who has the same stack')], default='talent is requested', max_length=300, null=True)),
                ('sdls_phase', models.CharField(blank=True, choices=[('Planning', 'Planning'), ('Defining', 'Defining'), ('Designing', 'Designing'), ('Building', 'Building'), ('Testing', 'Testing'), ('Deployment', 'Deployment')], default='SDLS Phase is not defined', max_length=300, null=True)),
                ('ocuppation', models.CharField(blank=True, choices=[('Data Scientist', 'Data Scientist'), ('Data Analyst', 'Data Analyst'), ('Data Engineer', 'Data Engineer'), ('ML Engineer', 'ML Engineer'), ('Machine Learning Scientist', 'Machine Learning Scientist'), ('Business Analyst', 'Business Analyst'), ('Marketing Analyst', 'Marketing Analyst'), ('Data Architect', 'Data Architect'), ('Applications Architect', 'Applications Architect'), ('Enterprise Architect', 'Enterprise Architect'), ('Infrastructure Architect', 'Infrastructure Architect'), ('Data and Analytics Manager', 'Data and Analytics Manager'), ('BI Analyst', 'BI Analyst'), ('BI Developer', 'BI Developer'), ('Statistician', 'Statistician'), ('Data Mining Specialist', 'Data Mining Specialist'), ('Database Administrator', 'Database Administrator'), ('Database Developer', 'Database Developer')], default='Ocuppation is not defined', max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_DS', to='post_DS.post_ds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user_DS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
