# Generated by Django 4.0.7 on 2023-04-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_DS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevancy_DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_relevancy_DS', to='post_DS.post_ds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relevancy_DS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conciseness_DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_conciseness_DS', to='post_DS.post_ds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conciseness_DS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
