# Generated by Django 4.0.7 on 2023-04-14 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_DS', '0003_alter_post_ds_clean_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_ds',
            name='clean_SCORE',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
