# Generated by Django 4.0.7 on 2023-04-12 16:11

import authy_DS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_DS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=80, verbose_name='last_name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=authy_DS.models.user_directory_path, verbose_name='Picture2_DS')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('industry_and_projects', models.TextField(choices=[('Business Projects', 'Business Projects'), ('Medicine', 'Medicine'), ('Agriculture Projects', 'Agriculture Projects'), ('Fintech', 'Fintech'), ('Blockchain', 'Blockchain'), ('Crypto Currency', 'Crypto Currency'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI'), ('Business', 'Business'), ('Analytics', 'Analytics'), ('ERP', 'ERP'), ('E-commerce', 'E-commerce'), ('Agriculture', 'Agriculture'), ('Data Science', 'Data Science'), ('Banking', 'Banking')])),
                ('location', models.CharField(max_length=150, verbose_name='address')),
                ('telephone', models.CharField(blank=True, max_length=80, null=True)),
                ('kaggle', models.CharField(blank=True, max_length=80, null=True)),
                ('github', models.CharField(blank=True, max_length=80, null=True)),
                ('linkedInn', models.CharField(blank=True, max_length=80, null=True)),
                ('previous_CTO_linkedInn_link', models.CharField(blank=True, max_length=80, null=True)),
                ('previous_HRmanager_linkedInn_link', models.CharField(blank=True, max_length=80, null=True)),
                ('favorites', models.ManyToManyField(blank=True, to='post_DS.post_ds')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_DS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
