# Generated by Django 4.0.7 on 2023-04-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('end_time', models.DateField(default=django.utils.timezone.now)),
                ('body', models.CharField(blank=True, choices=[('PAIR CODING', 'PAIR CODING'), ('INDIVIDUAL CODING', 'INDIVIDUAL CODING'), ('BEHAVORIAL INTERVIEW', 'BEHAVORIAL INTERVIEW'), ('SIMULATED PROJECTS', 'SIMULATED PROJECTS'), ('ASSIGNMENT CHECKING', 'ASSIGNMENT CHECKING')], max_length=300, null=True)),
                ('body2', models.CharField(blank=True, choices=[('can be changed', 'can be changed'), ('can not be changed', 'can not be changed')], max_length=300, null=True)),
                ('task_choice', models.CharField(blank=True, choices=[('GENERAL TASK', 'GENERAL TASK'), ('SPECIFIC TASK', 'SPECIFIC TASK')], max_length=300, null=True)),
                ('project_choice', models.CharField(blank=True, choices=[('SPECIFIC PROJECT', 'SPECIFIC PROJECT'), ('GRENERAL PROJECT', 'GRENERAL PROJECT')], max_length=300, null=True)),
                ('examine_types', models.CharField(blank=True, choices=[('CODING', 'CODING'), ('ORAL', 'ORAL'), ('CODING & ORAL', 'CODING & ORAL')], max_length=300, null=True)),
                ('task_method', models.CharField(blank=True, choices=[('LIVE INTERVIEW', 'LIVE INTERVIEW'), ('HOME ASSIGNMENT', 'HOME ASSIGNMENT'), ('LIVE & HOME ASSIGNMENT', 'LIVE & HOME ASSIGNMENT')], max_length=300, null=True)),
                ('task_completion', models.CharField(blank=True, choices=[('PAIR PROGRAMMING', 'PAIR PROGRAMMING'), ('INDIVIDUAL PROGRAMMING', 'INDIVIDUAL PROGRAMMING')], max_length=300, null=True)),
                ('sdls_phase', models.CharField(blank=True, choices=[('Planning', 'Planning'), ('Defining', 'Defining'), ('Designing', 'Designing'), ('Building', 'Building'), ('Testing', 'Testing'), ('Deployment', 'Deployment')], max_length=300, null=True)),
                ('evaluation_duration', models.CharField(blank=True, choices=[('1 day', '1 day'), ('2 days', '2 days'), ('3 days', '3 days'), ('4 days', '4 days'), ('5 days', '5 days'), ('6 days', '6 days'), ('1 week', '1 week'), ('1-2 weeks', '1-2 weeks'), ('2-3 weeks', '2-3 weeks')], max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_DS', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_DS', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_DS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
