# Generated by Django 4.0.7 on 2023-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessingFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('assesses algorithms', 'assesses algorithms'), ('assesses back-end language', 'assesses back-end language'), ('assesses back end frameworks', 'assesses back end frameworks'), ('assesses front-end frameworks', 'assesses front-end frameworks'), ('assesses soft skills ', 'assesses soft skills ')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('on-boarding process', 'on-boarding process'), ('salary negotiations', 'salary negotiations'), ('updating the assessment(with extra fee) ', 'updating the assessment(with extra fee) ')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviouralChallange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Works under pressure', 'Works under pressure'), ('Can not work under pressure', 'Can not work under pressure')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudComputing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Amazon Web Services (AWS)', 'Amazon Web Services (AWS)'), ('Microsoft Azure', 'Microsoft Azure'), ('Google Cloud Platform (GCP)', 'Google Cloud Platform (GCP)')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Clean', 'Clean'), ('Refactored', 'Refactored'), ('well documented', 'well documented'), ('Unit Tested', 'Unit Tested'), ('Debuged', 'Debuged'), ('Debuged with other team members', 'Debuged with other team members'), ('Debuged other team members bugs', 'Debuged other team members bugs'), ('Analyzed', 'Analyzed'), ('Analyzed with other team members', 'Analyzed with other team members'), ('Analyzed other team members script', 'Analyzed other team members script'), ('Discussed', 'Discussed'), ('Discussed with other team members', 'Discussed with other team members'), ('Expected problems are reasoned', 'Expected problems are reasoned'), ('Arbitrary problems are reasoned', 'Arbitrary problems are reasoned'), ('Expected constraints are reasoned', 'Expected constraints are reasoned'), ('Arbitrary constraints are reasoned', 'Arbitrary constraints are reasoned'), ('Designed with one approach.', 'Designed with one approach'), ('Designed with multiple possible approaches', 'Designed with multiple possible approaches')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratingWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hiring managers', 'hiring managers'), ('hr department', 'hr department'), ('CTO', 'CTO'), ('tech leads', 'tech leads'), ('product managers', 'product managers'), ('project managers', 'project managers')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Works with cross-functional teams', 'Works with cross-functional teams'), ('Higher management ', 'Higher management '), ('Software development project. ', 'Software development project. '), ('Expresses complex information to non-experts in the field', 'Expresses complex information to non-experts in the field'), ('Processes their needs against your own.', 'Processes their needs against your own.'), ('Presents software architectural overview. ', 'Presents software architectural overview. '), ('Consistent in efficiency and clarity', 'Consistent in efficiency and clarity'), ('Resolves a communication problem by thinking ', 'Resolves a communication problem by thinking '), ("Learns to see things from anther's perspective", "Learns to see things from anther's perspective"), ('Prevents conflict of ideas among the development team. ', 'Prevents conflict of ideas among the development team. '), ('Assess the various opinions', 'Assess the various opinions'), ('Feedback is solution based', 'Feedback is solution based'), ('Resistance to listening to objections or ideas. ', 'Resistance to listening to objections or ideas. '), ('Responds to this realization', 'Responds to this realization')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerScienceCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Algorithms and Data Structures Courses', 'Algorithms and Data Structures Courses'), ('STEM Courses', 'STEM Courses'), ('Artificial Intelligence Courses', 'Artificial Intelligence Courses'), ('Data Science Courses', 'Data Science Courses'), ('Mathematics Courses', 'Mathematics Courses'), ('Programming Languages Courses', 'Programming Languages Courses'), ('Software Development Courses', 'Software Development Courses'), ('Machine Learning Courses', 'Machine Learning Courses')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Docker', 'Docker'), ('AWS Fargate', 'AWS Fargate'), ('Google Kubernetes Engine', 'Google Kubernetes Engine'), ('Amazon ECS', 'Amazon ECS'), ('Linux Containers', 'Linux Containers'), ('Microsoft Azure Container Services', 'Microsoft Azure Container Services'), ('Database systems', 'Database systems'), ('Computer networking', 'Computer networking'), ('Data structures and algorithms', 'Data structures and algorithms'), ('Computer security', 'Computer security'), ('Distributed systems', 'Distributed systems'), ('Software development', 'Software development'), ('Operating systems', 'Operating systems'), ('Programming languages', 'Programming languages'), ('Advanced Computer Architecture', 'Advanced Computer Architecture')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataBaseSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RDMS | MySQL', 'RDMS | MySQL'), ('DBMS | NoSQL', 'DBMS | NoSQL'), ('DBMS | MongoDB', 'DBMS | MongoDB')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataStructuresAndAlgorithms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Primitive Types ', 'Primitive Types '), ('Convert base ', 'Convert base '), ('Arrays', 'Arrays'), ('Compute the max difference ', 'Compute the max difference '), ('Strings', 'Strings'), ('Interconvert strings and integers', 'Interconvert strings and integers'), ('Reverse all the words in a sentence', 'Reverse all the words in a sentence'), ('Linked Lists ', 'Linked Lists '), ('Test for cyclicity', 'Test for cyclicity'), ('Stacks and Queues ', 'Stacks and Queues '), ('Implement a stack with max API ', 'Implement a stack with max API '), ('Print a binary tree in order of increasing depth ', 'Print a binary tree in order of increasing depth '), ('Binary Trees', 'Binary Trees'), ('Test if a binary tree is balanced', 'Test if a binary tree is balanced'), ('Heaps', 'Heaps'), ('Merge sorted files', 'Merge sorted files'), ('Searching', 'Searching'), ('Search a sorted array for first occurrence of k', 'Search a sorted array for first occurrence of k'), ('Hash Tables ', 'Hash Tables '), ('Test if an anonymous letter is constructible', 'Test if an anonymous letter is constructible'), ('Sorting', 'Sorting'), ('Compute the intersection of two sorted arrays', 'Compute the intersection of two sorted arrays'), ('Binary Search Trees ', 'Binary Search Trees '), ('Test if a binary tree satisfies the BST property', 'Test if a binary tree satisfies the BST property'), ('Recursion', 'Recursion'), ('Enumerate the power set', 'Enumerate the power set'), ('Dynamic Programming ', 'Dynamic Programming '), ('Count the number of ways to traverse a 2D array ', 'Count the number of ways to traverse a 2D array '), ('Greedy Algorithms and Invariants ', 'Greedy Algorithms and Invariants '), ('The 3-sum problem', 'The 3-sum problem'), ('Graphs', 'Graphs'), ('Paint a Boolean matrix', 'Paint a Boolean matrix'), ('Parallel Computing', 'Parallel Computing'), ('Implement a Timer class ', 'Implement a Timer class '), ('Design Problems ', 'Design Problems '), ('Design a system for detecting copyright infringement', 'Design a system for detecting copyright infringement')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Secondary', 'Secondary'), ('Bachelor', 'Bachelor'), ('MA', 'MA'), ('MB', 'MB'), ('MBA', 'MBA'), ('PhD', 'PhD')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('3-5', '3-5'), ('5-10', '5-10'), ('10-15', '10-15'), ('more than 15', 'more than 15'), ('________', '________'), ('________', '________'), ('________', '________'), ('________', '________')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FocusStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Goal orientated', 'Goal orientated'), ('Action-oriented', 'Action-oriented'), ('Result oriented', 'Result oriented')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Django', 'Django'), ('ExpressJS', 'ExpressJS'), ('Laravel', 'Laravel'), ('Ruby on Rails', 'Ruby on Rails'), ('CakePHP', 'CakePHP'), ('Flask', 'Flask'), ('ASP .NET Core', 'ASP .NET Core'), ('Spring Boot', 'Spring Boot'), ('Koa', 'Koa'), ('Phoenix', 'Phoenix')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkFrontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript\xa0', 'JavaScript\xa0'), ('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('TypeScript\xa0', 'TypeScript\xa0'), ('Elm', 'Elm'), ('jQuery', 'jQuery'), ('Swift\xa0', 'Swift\xa0')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Visual Studio', 'Visual Studio'), ('Visual Studio Code', 'Visual Studio Code'), ('AWS Cloud9', 'AWS Cloud9'), ('SlickEdit', 'SlickEdit'), ('Eclipse Theia', 'Eclipse Theia'), ('IntelliJ IDEA', 'IntelliJ IDEA'), ('PyCharm', 'PyCharm'), ('Xcode', 'Xcode'), ('NetBeans', 'NetBeans'), ('GNAT Studio', 'GNAT Studio'), ('Eclipse', 'Eclipse')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedSDLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Planning Stage', 'Planning Stage'), ('Requirements of Analysis Stage', 'Requirements of Analysis Stage'), ('Design and Prototyping Stage', 'Design and Prototyping Stage'), ('Software Development Stage', 'Software Development Stage'), ('Software Testing Stage', 'Software Testing Stage'), ('Implementation and Integration', 'Implementation and Integration'), ('Operations and Maintenance Stage', 'Operations and Maintenance Stage')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPerformence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Plans', 'Plans'), ('Researches', 'Researches'), ('Analysis', 'Analysis'), ('Systems analysis', 'Systems analysis'), ('Analyzes reported', 'Analyzes reported'), ('Makes determinations', 'Makes determinations'), ('Develops the solution', 'Develops the solution'), ('Designs system specifications', 'Designs system specifications'), ('Designs standards', 'Designs standards'), ('Designs programming', 'Designs programming'), ('Gains approvals', 'Gains approvals'), ('Improves operations', 'Improves operations'), ('Implementing a software solution', 'Implementing a software solution'), ('Conducts a specific task', 'Conducts a specific task'), ('Makes decision when handover to the software testing team', 'Makes decision when handover to the software testing team'), ('Analyses a software development lifecycle.', 'Analyses a software development lifecycle.'), ('Develops a software development lifecycle.', 'Develops a software development lifecycle.'), ('Works autonomously on an operational feasibility task. ', 'Works autonomously on an operational feasibility task.'), ('Develops software project from build to release', 'Develops software project from build to release')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Arabic', 'Arabic'), ('French', 'French'), ('Turkish', 'Turkish')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('GO', 'GO'), ('Ruby', 'Ruby'), ('Scala', 'Scala'), ('JADE', 'JADE'), ('Emerald', 'Emerald'), ('Visual Basic .NET', 'Visual Basic .NET'), ('PHP', 'PHP'), ('JavaScript', 'JavaScript')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Independent judgment as a senior team member ', 'Independent judgment as a senior team member '), ('Chooses a leadership through team autonomy methodology', 'Chooses a leadership through team autonomy methodology'), ('Deals with issues arose', 'Deals with issues arose'), (' Motivates the team', ' Motivates the team'), ('Challenges and rewards the team', 'Challenges and rewards the team'), ('Can have methods of stimulation the team', 'Can have methods of stimulation the team'), ('Involves the team while effectively taking charge', 'Involves the team while effectively taking charge'), ('Assesses expert opinions against the noise', 'Assesses expert opinions against the noise')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(' Can have technical solution for complex and potentially unique software problem.', ' Can have technical solution for complex and potentially unique software problem.'), ('Assess the problem', 'Assess the problem'), ('Undertakes research and analysis', 'Undertakes research and analysis'), ('Manages risk', 'Manages risk'), ('Uses external resource(stack overflow, etc)', 'Uses external resource(stack overflow, etc)'), ('Researches to understand of business needs within your company.', 'Researches to understand of business needs within your company.'), ('Learns and adapts quickly.', 'Learns and adapts quickly.'), ('Assess the technical specifications', 'Assess the technical specifications')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAndervices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('application development', 'application development'), ('game development', 'game development'), ('software development analytics tools', 'software development analytics tools'), ('web frameworks', 'web frameworks'), ('web designing services', 'web designing services'), ('help desk it services', 'help desk it services'), ('virtual desktops', 'virtual desktops'), ('CRM', 'CRM'), ('software testing', 'software testing'), ('test management', 'test management'), ('network security', 'network security'), ('data storage and management', 'data storage and management'), ('data security', 'data security'), ('data backups', 'data backups'), ('tech/it support', 'tech/it support'), ('file servers', 'file servers'), ('email', 'email'), ('cloud services', 'cloud services'), ('PAAS (cloud platform as a service)', 'PAAS (cloud platform as a service)'), ('IDE  (integrated development environments)', 'IDE  (integrated development environments)')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('has seen this exact problem before', 'has seen this exact problem before'), ('has seen this similar problem before', 'has seen this exact problem before'), ('has not seen the problem and field at all', 'has not seen the problem and field at all')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pay raises ', 'pay raises '), ('fitness', 'fitness'), ('free meals', 'free meals'), ('retirement benefits', 'retirement benefits'), ('retirement planning services', 'retirement planning services'), ('college debt relief', 'college debt relief'), ('use of a company car', 'use of a company car'), ('pensions and stock options', 'pensions and stock options'), ('discounts on company products and services; housing', 'discounts on company products and services; housing'), ('other optional benefits', 'other optional benefits')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedInsuranceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('health insurance', 'health insurance'), ('dental insurance', 'dental insurance'), ('vision care', 'vision care'), ('life insurance', 'life insurance'), ('legal insurance', 'legal insurance'), ('pet insurance', 'pet insurance')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedVacationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paid vacation leave', 'paid vacation leave'), ('personal leave', 'personal leave'), ('sick leave ', 'sick leave '), ('child care', 'child care'), ('breaks', 'breaks'), ('flexible schedules', 'flexible schedules')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SdlcPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('_______', '_______')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Communication (verbal and written)', 'Communication (verbal and written)'), ('Teamwork and conflict resolution', 'Teamwork and conflict resolution'), ('Problem solving', 'Problem solving'), ('Empathy', 'Empathy'), ('Patience', 'Patience'), ('Curiosity', 'Curiosity'), ('Adaptability', 'Adaptability'), ('Accountability', 'Accountability'), ('Time management', 'Time management')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolvingApproachGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Creative & Problem Solver', 'Creative & Problem Solver'), ('Uncreative', 'Uncreative')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolvingApproachSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('regurgitated the solution the candidate already knew', 'regurgitated the solution the candidate already knew'), ('managed to piece together a similar solution that is correct', 'managed to piece together a similar solution that is correct'), ('happens to have an interest in the field related to the problem domain', 'happens to have an interest in the field related to the problem domain')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teamwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Confers with users in the development of a software solution.', 'Confers with users in the development of a software solution.'), ('Mentors software developers', 'Mentors software developers'), ('Resolve a Disagreement on Implementation', 'Resolve a Disagreement on Implementation')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CTO', 'CTO'), ('software engeneer', 'software engeneer'), ('data science', 'data science'), ('ML engeneer', 'ML engeneer')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Database and SQL', 'Database and SQL'), ('Object-oriented programming (OOP) languages', 'Object-oriented programming (OOP) languages'), ('Integrated development environments (IDEs)', 'Integrated development environments (IDEs)'), ('Cloud computing', 'Cloud computing'), ('Web development', 'Web development'), ('Containers', 'Containers'), ('Text editors', 'Text editors'), ('Git version control', 'Git version control')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextEditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Visual Studio Code', 'Visual Studio Code'), ('Sublime Text', 'Sublime Text'), ('Notepad++', 'Notepad++'), ('UltraEdit', 'UltraEdit')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(' Developed personal management method ', ' Developed personal management method '), (' Management method for hectic multi-tasking ', ' Management method for hectic multi-tasking '), ('Management method for setting specific periods for a single task.', 'Management method for setting specific periods for a single task.'), ('Has experience in enhancing timelines and productivity.', 'Has experience in enhancing timelines and productivity.'), ('Delegates task on time', 'Delegates task on time'), ('Chooses team members to work on specific tasks', 'Chooses team members to work on specific tasks'), ('Creates small team units to work together', 'Creates small team units to work together'), ('Implements a time management methodology across the software development team.', 'Implements a time management methodology across the software development team.'), ('Strictly prioritizes tasks as part of others’ time management strategy.', 'Strictly prioritizes tasks as part of others’ time management strategy.'), ('Prioritizes over other tasks', 'Prioritizes over other tasks'), ('Incorporates team timelines and needs into this', 'Incorporates team timelines and needs into this')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('API', 'API'), ('Chrome Developer Tools', 'Chrome Developer Tools'), ('jQuery', 'jQuery'), ('GitHub', 'GitHub'), ('CodePen', 'CodePen'), ('Angular.js', 'Angular.js'), ('Sass', 'Sass')], max_length=200, null=True)),
            ],
        ),
    ]
